site:
  title: How I Code
  url: https://howicode.ericscouten.com
  start_page: ROOT::index.adoc

content:
  sources:
  - url: .
    branches: HEAD
    start_path: docs

ui:
  bundle:
    url: ./custom-ui/

output:
  dir: ./build
