= How I Code
:page-disable-breadcrumbs:
:page-disable-comments:
:page-disable-date:

*Hi, I'm Eric.* I've been https://ericscouten.dev/about/[writing code for a few decades now] and, like most people who've been at this for a while, I've developed some habits and ways of thinking about code.

Honestly, I'm sharing these thoughts as much for myself as for you -- it's been a fun exercise trying to put into words things I've been doing intuitively for years.
I'm not trying to tell you how you should code (that would be kind of presumptuous!), but maybe some of these ideas will resonate with you or get you thinking about your own approach.

For the last few years, I've been writing primarily in the https://www.rust-lang.org[Rust programming language], so my examples will be almost exclusively in Rust.
If you write in a different language, you might find some things that apply and some that don't. No worries; it's all good.

NOTE: I suppose this site could be called _How I *Think* About Code,_ but that title wouldn't be as pithy.

== Navigating

I've arranged these pages in a loose sequence that you can follow using the “Next” and “Previous” links at the bottom of each page.
That said, feel free to jump around. There's a table of contents on the left (if you're on a bigger screen) that'll help you find whatever catches your interest.
I hope you find something useful here, however you choose to explore!
