= Use complete sentences

When possible (and it's possible most of the time), write in complete sentences.

This applies in almost all contexts with a few specific adaptations.

== Comments

I almost always write comments in complete sentences with sentence-style punctuation.

.Comments in complete sentences
[source.prefer,rust]
----
// Recursively apply passthrough replacement and write the result.
let replacer = PassthroughRestoreReplacer(self.0, self.1);
----

.Comments not formatted as a sentence
[source.avoid,rust]
----
// recursively apply passthrough replacement and write the result
let replacer = PassthroughRestoreReplacer(self.0, self.1);
----

[#exception-section-titles-and-captions]
== Exception: Section titles and captions

As you'll see throughout this site, I don't jump through hoops to make section titles and captions into complete sentences.
I use complete sentences where they make sense -- as, for example, the title of this page, “Use complete sentences.”
But this section's title, <<exception-section-titles-and-captions>>, is not a complete sentence.

Either way, I almost always format titles and captions xref:language/sentence-case.adoc[using sentence case].

Because they may or may not be complete sentences, I never add a trailing period on section titles or captions.
