= I use complete sentences

Most of the time, I write comments and documentation using complete sentences.

It's not always necessary, but it usually makes things clearer and more professional-looking.

== Comments

I almost always write comments as complete sentences, with proper punctuation.

.Comments in complete sentences
[source.prefer,rust]
----
// Recursively apply passthrough replacement and write the result.
let replacer = PassthroughRestoreReplacer(self.0, self.1);
----

.Comments not formatted as a sentence
[source.avoid,rust]
----
// recursively apply passthrough replacement and write the result
let replacer = PassthroughRestoreReplacer(self.0, self.1);
----

[#exception-titles-and-captions]
== Exception: Titles and captions

As you can see throughout this site, I don't force titles and captions to be complete sentences when it would sound awkward.
Sometimes it works (like the title of this page), but other times it's more natural to use a phrase (like this section's title).

Either way, I format titles and captions xref:language/sentence-case.adoc[using sentence case].

Since they might or might not be complete sentences, I skip the trailing period on titles and captions.
