= Use sentence case

Like many developers and documentation guidelines, I have chosen to use _sentence case_ consistently in most contexts.

The https://learn.microsoft.com/en-us/style-guide/capitalization[_Microsoft Writing Style Guide_ section on capitalization^] has largely shaped my own thinking.
I'll summarize a few of their key points, which I follow:

* Use sentence-style capitalization most of the time. That means the first word and proper nouns are capitalized; everything else is in lower case.
* Avoid the use of all upper case words for emphasis. _(Except: See <<upper-case-admonitions>>.)_
* Use title case for proper nouns (names of things).

As an example, I use title case for the name of this site, _How I Code,_ but the title for each page and the section headings within the pages are in sentence case.

[#upper-case-admonitions]
== Exception: Use all capitals for admonitions

I make one exception to the “avoid use of all upper case words ...” guideline for _admonitions_.
Admonitions are things like TEMPORARY, WARNING, NOTE, etc. that preface a specific category of content.

You'll notice that I use all capitals (albeit in sized smaller than most other text) when styling this site, as in the following examples:

.Admonition in all caps
[source.prefer,rust]
----
// FIXME: We probably shouldn't even get here when the link:
// prefix is present. The regex is doing too much.
----

.Admonition blends in with surrounding text
[source.avoid,rust]
----
// fixme we probably shouldn't even get here when the link:
// prefix is present. The regex is doing too much.
----
